### PR TITLE
feat: migrate to capacitor 3

### LINKED ISSUE #9: Capacitor 3
Hello,

Are you going to update this plugin to adapt it to Capacitor v3 ?

Thank you

### PR DESCRIPTION
**Pull request by thesayyn**
fixes #9

### CODE REVIEW

**Comment by Odonno** [comment]
Hi there,

This library looks really cool and we are in a need of this package for a project using Capacitor 3.

Are you able to complete this PR or do you need any help?

**Comment by riderx** [comment]
@thesayyn can you publish your module i will add it to : https://github.com/riderx/awesome-capacitor instead of this one

**Comment by sverdlov** [comment]
@SpellChucker @thesayyn I will be very grateful if any of you publish plug-in version for Capacitor 3.

**Comment by thesayyn** [comment]
it is ready so it is up to the maintainer to merge this. I don't want to maintain yet another abandoned oss project.

**Comment by riderx** [comment]
i do not understand why people never merge, it's free to do

**Comment by thesayyn** [comment]
seems like the project is abandoned. so no surprises

**Comment by rgustavsson** [comment]
How are you guys managing facebook analytics in capacitor 3 now?

**Comment by sverdlov** [comment]
@rgustavsson you can use one of forks. For example my 
`npm i sverdlov/capacitor-plugin-facebook-analytics`

**Comment by rgustavsson** [comment]
Thank you @sverdlov

**Pull request closed without merging**
